[package]
name = "vos"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = { version = "2.3.1", default-features = false, optional = true }
futures-util = { version = "0.3.30", default-features = false, features = ["sink"], optional = true }
log = "0.4.22"
serde = { version = "1.0.209", default-features = false }
vos-macro = { path = "./vos-macro" }
# Native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# axum = { version = "0.7.7", default-features = false }
matrix-sdk = { version = "0.7.1", default-features = false, features = ["native-tls", "e2e-encryption", "sqlite"], optional = true }
tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread", "macros"] }

# JS
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.93", default-features = false }
wasm-bindgen-futures = { version = "0.4.42", default-features = false }
wasm-logger = { version = "0.2.0", default-features = false }
serde-wasm-bindgen = "0.6.5"
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.69"
features = [
  "Window",
  # "Worker",
  "DedicatedWorkerGlobalScope",
  "MessageEvent",
]
[target.'cfg(target_arch = "wasm32")'.dependencies.matrix-sdk]
version = "0.7.1"
default-features = false
features = [
  "js",
  "native-tls",
  "e2e-encryption",
  "indexeddb",
]
optional = true

[features]
default = ["shell"]
shell = [
  "dep:async-channel",
  "dep:futures-util",
  "dep:matrix-sdk",
]

[lib]
crate-type = ["cdylib", "rlib"]
