[workspace]
members = [
  "vos-macro",
  "programs/echo",
]

[package]
name = "vos"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", default-features = false }
edge-net = "0.10.1"
# defmt = "0.3.8"
embassy-executor = { version = "0.7", features = ["nightly"] }
embassy-sync = "0.6"
embassy-time = "0.4"
embedded-alloc = "0.6.0"
embedded-io-async = "0.6.1"
futures-concurrency = { version = "7.6.3", default-features = false }
heapless = { version = "0.8.0", features = ["serde"] }
log = "0.4.22"
noline = "0.5.1"
nu-engine = { version = "0.101.0", default-features = false, optional = true }
nu-parser = { version = "0.101.0", default-features = false, optional = true }
rand = { version = "0.8.5", default-features = false }
serde = { version = "1.0.209", default-features = false, features = ["derive", "alloc"] }
static_cell = { version = "2.1.0", features = ["nightly"] }
vos-macro = { path = "./vos-macro" }
wasmi = { version = "0.39.1", default-features = false }
sunset = { version = "0.2", git = "https://github.com/mkj/sunset.git", branch = "main", optional = true }
sunset-embassy = { version = "0.2", git = "https://github.com/mkj/sunset.git", branch = "main", optional = true }
ed25519-dalek = { version = "2.1.1", default-features = false, features = ["zeroize", "serde"], optional = true }

# Native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# axum = { version = "0.7.7", default-features = false }
env_logger = { version = "0.11.5", optional = true }
# critical-section = { version = "1.1", optional = true }
matrix-sdk = { version = "0.7.1", default-features = false, features = ["native-tls", "e2e-encryption", "sqlite"], optional = true }
# tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread", "macros"] }
mimalloc = { version = "0.1.43", optional = true }

# JS
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.93", default-features = false, optional = true }
wasm-bindgen-futures = { version = "0.4.42", default-features = false, optional = true }
wasm-logger = { version = "0.2.0", default-features = false, optional = true }
serde-wasm-bindgen = { version = "0.6.5", optional = true }
[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.69"
features = [
  "Window",
  # "Worker",
  "DedicatedWorkerGlobalScope",
  "MessageEvent",
]
optional = true
[target.'cfg(target_arch = "wasm32")'.dependencies.matrix-sdk]
version = "0.7.1"
default-features = false
features = [
  "js",
  "native-tls",
  "e2e-encryption",
  "indexeddb",
]
optional = true

[features]
default = ["std"]
std = ["os-std"]
os-std = [
  "port-http",
  "port-ssh",
  "nu",
  # "critical-section/std",
  "edge-net/std",
  "embassy-executor/arch-std",
  "embassy-executor/executor-thread",
  "embassy-executor/log",
  "embassy-sync/std",
  "embassy-time/std",
  "rand/std_rng",
  "wasmi/std",

  "dep:env_logger",
  "dep:mimalloc"
]

web = ["os-web"]
os-web = [
  "embassy-executor/arch-wasm",
  "embassy-executor/executor-thread",
  "embassy-executor/log",

  # "critical-section?/std",
  "embassy-time/wasm",
  # "getrandom/js",
  "dep:web-sys",
  "dep:wasm-bindgen",
  "dep:wasm-bindgen-futures",
  "dep:wasm-logger",
  "dep:serde-wasm-bindgen",
]

rv = ["os-rv"]
os-rv = [
  "embassy-executor/arch-riscv32",
  "embassy-executor/executor-thread",
  "embassy-executor/log",
  "rand/std_rng",
]

port-http = ["edge-net/io"]
port-ssh = ["dep:sunset", "dep:sunset-embassy", "dep:ed25519-dalek"]
nu = ["dep:nu-engine", "dep:nu-parser"]

# default = ["shell-std"]
# shell-std = [
  # "dep:async-channel",
  # "dep:futures-util",
  # "dep:matrix-sdk",
# ]

[lib]
crate-type = ["cdylib", "rlib"]
