[workspace]
members = [
  "vos-macro",
  "os",
  "programs/echo",
  "programs/http-server",
]

[package]
name = "vos"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
miniserde = { workspace = true }
env_logger = { version = "0.11.5", optional = true }
os = { path = "./os", package = "vos-os", optional = true }
# bin
vos-macro = { path = "./vos-macro", optional = true }
wstd = { version = "0.5.1", optional = true }

[workspace.dependencies]
log = "0.4.22"
miniserde = { version = "0.1.41", default-features = false }

[features]
bin = ["dep:vos-macro", "dep:wstd"]
os-std = ["os/std", "dep:env_logger"]
os-rv = ["os/rv"]
os-web = ["os/web"]
