[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
picoserve = { version = "0.13.1", features = ["std"] }
serde = { version = "1.0.216", features = ["derive"] }
wstd = "0.5.0-draft1"
